apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator
  namespace: openshift-operators
spec:
  channel: dev-preview
  installPlanApproval: Automatic
  name: openshift-pipelines-operator
  source: installed-openshift-pipelines
  sourceNamespace: openshift-operators
  startingCSV: openshift-pipelines-operator.v1.2.1
